# Variáveis de ambiente locais
@baseUrl = http://localhost:3000/




### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "uid": "email@email.com",
    "password": "1234567a"
}

> {%
    // Salva o token da resposta em uma variável global
    client.global.set("auth_token", response.body['accessToken']);
%}





### Register house
POST {{baseUrl}}/house
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "identifier": "Casa 1",
    "townhouseId": 1
}





### Register user
POST {{baseUrl}}/user/register
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "firstName": "Caique",
    "lastName": "Duarte",
    "password": "1234567a",
    "email": "",
    "phone": "0",
    "houseId": 1
}


### Get user
GET {{baseUrl}}/user/bcf0b5e3-6d85-4726-8552-7ac4e424d81f
Authorization: Bearer {{auth_token}}


### Get all users
GET {{baseUrl}}/user/all
Authorization: Bearer {{auth_token}}


### Post condomínio
POST {{baseUrl}}/townhouse
Content-Type: application/json

{
  "name": "Corumbá 2"
}





### Get condomínio
GET {{baseUrl}}/townhouse


### Delete condomínio
DELETE {{baseUrl}}/townhouse/2


### Update condomínio
PATCH {{baseUrl}}/townhouse/3
Content-Type: application/json

{
    "name": "Corumbá 3"
}
