export enum UserAuditAction {
    CREATED = 'CREATED',
    REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED',
    UPDATED = 'UPDATED',
    APPROVED = 'APPROVED',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    ACTIVATED = 'ACTIVATED',
}
